version: '3.4'

services:
  login.api:
    container_name: login.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DockerConnection=Server=sqlserver;Port=1433;Database=MicrosservicePraticle;User=sa;Password=Fern@nd01331;
    depends_on:
      - sqlserver
    ports:
      - "8001:80"

  sqlserver:
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      SA_PASSWORD: "Fern@nd01331"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"