version: '3.4'

services:
  sqlserver:
    image: sqlserver

  login.api:
    image: ${DOCKER_REGISTRY-}loginapi
    build:
      context: .
      dockerfile: Login.API/Dockerfile

  usuario.get:
    image: ${DOCKER_REGISTRY-}usuarioget
    build:
      context: .
      dockerfile: Usuario.get/Dockerfile

  usuario.post:
    image: ${DOCKER_REGISTRY-}usuariopost
    build:
      context: .
      dockerfile: Usuario.post/Dockerfile
  
  usuario.put:
    image: ${DOCKER_REGISTRY-}usuarioput
    build:
      context: .
      dockerfile: Usuario.put/Dockerfile

  usuario.del:
    image: ${DOCKER_REGISTRY-}usuariodel
    build:
      context: .
      dockerfile: Usuario.del/Dockerfile
 
