version: '3.4'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      MSSQL_SA_PASSWORD: "******"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

  login.api:
    container_name: login.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DockerConnection=Server=sqlserver;Database=MicrosservicePraticle;User ID=sa;Password=******;Connect Timeout=30;Encrypt=False;TrustServerCertificate=True;ApplicationIntent=ReadWrite;MultiSubnetFailover=False;
    depends_on:
      - sqlserver
    ports:
      - "8001:8080"
    
  usuario.get:
    container_name: usuario.get
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DockerConnection=Server=sqlserver;Database=MicrosservicePraticle;User ID=sa;Password=******;Connect Timeout=30;Encrypt=False;TrustServerCertificate=True;ApplicationIntent=ReadWrite;MultiSubnetFailover=False;
    depends_on:
      - sqlserver
    ports:
      - "8002:8080"

  usuario.post:
    container_name: usuario.post
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DockerConnection=Server=sqlserver;Database=MicrosservicePraticle;User ID=sa;Password=******;Connect Timeout=30;Encrypt=False;TrustServerCertificate=True;ApplicationIntent=ReadWrite;MultiSubnetFailover=False;
    depends_on:
      - sqlserver
    ports:
      - "8003:8080"

  usuario.put:
    container_name: usuario.put
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ConnectionStrings__DockerConnection=Server=sqlserver;Database=MicrosservicePraticle;User ID=sa;Password=******;Connect Timeout=30;Encrypt=False;TrustServerCertificate=True;ApplicationIntent=ReadWrite;MultiSubnetFailover=False;
    depends_on:
        - sqlserver
    ports:
        - "8004:8080"

  usuario.del:
    container_name: usuario.del
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ConnectionStrings__DockerConnection=Server=sqlserver;Database=MicrosservicePraticle;User ID=sa;Password=******;Connect Timeout=30;Encrypt=False;TrustServerCertificate=True;ApplicationIntent=ReadWrite;MultiSubnetFailover=False;
    depends_on:
        - sqlserver
    ports:
        - "8005:8080"



