version: '3.4'

services:
  sqlserver:
    image: sqlserver

  login.api:
    image: ${DOCKER_REGISTRY-}loginapi
    build:
      context: .
      dockerfile: Login.API\Dockerfile

  usuario.get:
    image: ${DOCKER_REGISTRY-}usuarioget
    build:
      context: .
      dockerfile: Usuario.get\Dockerfile

